version: "3.9"

services:
  fastapi:
    image: sentiment-analysis-fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - .:/app